{
 "title": "GitLab users",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "GitLab 1 day ago",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commits per repo 1 day ago",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "topk(100,max_over_time(gitlab_repo_commits{job=\"exporter-gitlab-users-day\"}[5m])>0)",
       "legendFormat": "{{project_name}} / {{project_id}}"
      }
     ]
    },
    {
     "title": "Commits per user 1 month ago",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 10, "x": 10, "y": 1 },
     "targets": [
      {
       "expr": "topk(100,max_over_time(gitlab_user_commits{job=\"exporter-gitlab-users-day\"}[5m])>0)  ",
       "legendFormat": "{{user_email}}"
      }
     ]
    },
    {
     "title": "Total users 1 day ago",
     "type": "stat",
     "description": "Number of users in the referenced GitLab group",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gitlab_total_users{job=\"exporter-gitlab-users-day\"}[5m]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active users 1 day ago",
     "type": "stat",
     "description": "Number of active users in last day (user that did a git commit)",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gitlab_active_users{job=\"exporter-gitlab-users-day\"}[5m]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Passive users 1 day ago",
     "type": "stat",
     "description": "Number of passive users (that did login to GitLab web but did not do any commit)",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gitlab_passive_users{job=\"exporter-gitlab-users-day\"}[5m]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Repositories 1 day ago",
     "type": "stat",
     "description": "Number of all repositories including personal ones.",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gitlab_total_repositories{job=\"exporter-gitlab-users-day\"}[5m]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Commits 1 day ago",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gitlab_total_commits{job=\"exporter-gitlab-users-day\"}[5m]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Lines added per repo 1 day ago",
     "type": "barchart",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "topk(100,max_over_time(gitlab_repo_lines_added{job=\"exporter-gitlab-users-day\"}[5m])>0)",
       "legendFormat": "{{project_name}} / {{project_id}}"
      }
     ]
    },
    {
     "title": "Lines removed per repo 1 day ago",
     "type": "barchart",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 11 },
     "targets": [
      {
       "expr": "topk(100,max_over_time(gitlab_repo_lines_removed{job=\"exporter-gitlab-users-day\"}[5m])>0)",
       "legendFormat": "{{project_name}} / {{project_id}}"
      }
     ]
    },
    {
     "title": "Lines added per user 1 day ago",
     "type": "barchart",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 11 },
     "targets": [
      {
       "expr": "topk(100,max_over_time(gitlab_user_lines_added{job=\"exporter-gitlab-users-day\"}[5m])>0)",
       "legendFormat": "{{user_email}}"
      }
     ]
    },
    {
     "title": "Lines added per user 1 day ago",
     "type": "barchart",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 11 },
     "targets": [
      {
       "expr": "topk(100,max_over_time(gitlab_user_lines_removed{job=\"exporter-gitlab-users-day\"}[5m])>0)",
       "legendFormat": "{{user_email}}"
      }
     ]
    },
    {
     "title": "Total lines added 1 day ago",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gitlab_total_lines_added{job=\"exporter-gitlab-users-day\"}[5m]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total lines removed 1 day ago",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gitlab_total_lines_removed{job=\"exporter-gitlab-users-day\"}[5m]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "GitLab 1 month ago", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Commits per repo 1 month ago",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "topk(100,max_over_time(gitlab_repo_commits{job=\"exporter-gitlab-users-month\"}[5m])>0)",
     "legendFormat": "{{project_name}} / {{project_id}}"
    }
   ]
  },
  {
   "title": "Commits per user 1 month ago",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 2 },
   "targets": [
    {
     "expr": "topk(100,max_over_time(gitlab_user_commits{job=\"exporter-gitlab-users-month\"}[5m])>0)  ",
     "legendFormat": "{{user_email}}"
    }
   ]
  },
  {
   "title": "Total users 1 month ago",
   "type": "stat",
   "description": "Number of users in the referenced GitLab group",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_total_users{job=\"exporter-gitlab-users-month\"}[5m]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active users 1 month ago",
   "type": "stat",
   "description": "Number of active users in last day (user that did a git commit)",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_active_users{job=\"exporter-gitlab-users-month\"}[5m]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Passive users 1 month ago",
   "type": "stat",
   "description": "Number of passive users (that did login to GitLab web but did not do any commit)",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_passive_users{job=\"exporter-gitlab-users-month\"}[5m]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repositories 1 month ago",
   "type": "stat",
   "description": "Number of all repositories including personal ones.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_total_repositories{job=\"exporter-gitlab-users-month\"}[5m]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commits 1 month ago",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_total_commits{job=\"exporter-gitlab-users-month\"}[5m]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lines added per repo 1 month ago",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(100,max_over_time(gitlab_repo_lines_added{job=\"exporter-gitlab-users-month\"}[5m])>0)",
     "legendFormat": "{{project_name}} / {{project_id}}"
    }
   ]
  },
  {
   "title": "Lines removed per repo 1 month ago",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 12 },
   "targets": [
    {
     "expr": "topk(100,max_over_time(gitlab_repo_lines_removed{job=\"exporter-gitlab-users-month\"}[5m])>0)",
     "legendFormat": "{{project_name}} / {{project_id}}"
    }
   ]
  },
  {
   "title": "Lines added per user 1 month ago",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 12 },
   "targets": [
    {
     "expr": "topk(100,max_over_time(gitlab_user_lines_added{job=\"exporter-gitlab-users-month\"}[5m])>0)",
     "legendFormat": "{{user_email}}"
    }
   ]
  },
  {
   "title": "Lines added per user 1 month ago",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 12 },
   "targets": [
    {
     "expr": "topk(100,max_over_time(gitlab_user_lines_removed{job=\"exporter-gitlab-users-month\"}[5m])>0)",
     "legendFormat": "{{user_email}}"
    }
   ]
  },
  {
   "title": "Total lines added 1 month ago",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_total_lines_added{job=\"exporter-gitlab-users-month\"}[5m]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total lines removed 1 month ago",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_total_lines_removed{job=\"exporter-gitlab-users-month\"}[5m]",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GitLab timespan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active + Passive users in last 12 months",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max_over_time(gitlab_total_users_timespan_months[1h])",
     "legendFormat": "in past: {{in_past}}"
    }
   ]
  },
  {
   "title": "Active + Passive users in last 4 weeks",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "max_over_time(gitlab_total_users_timespan_weeks[1h])",
     "legendFormat": "in past: {{in_past}}"
    }
   ]
  },
  {
   "title": "Active + Passive users in last 30 days",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "max_over_time(gitlab_total_users_timespan_days[10m])",
     "legendFormat": "in past: {{in_past}}"
    }
   ]
  },
  {
   "title": "Commits in last 12 months",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max_over_time(gitlab_total_commits_timespan_months[1h])",
     "legendFormat": "in past: {{in_past}}"
    }
   ]
  },
  {
   "title": "Commits in last 4 weeks",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "max_over_time(gitlab_total_commits_timespan_weeks[1h])",
     "legendFormat": "in past: {{in_past}}"
    }
   ]
  },
  {
   "title": "Commits in last 30 days",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 24 },
   "targets": [
    {
     "expr": "max_over_time(gitlab_total_commits_timespan_days[10m])",
     "legendFormat": "in past: {{in_past}}"
    }
   ]
  },
  {
   "title": "Repositories in last 12 months",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "max_over_time(gitlab_total_repositories_timespan_months[1h])",
     "legendFormat": "in past: {{in_past}}"
    }
   ]
  },
  {
   "title": "Repositories in last 4 weeks",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "max_over_time(gitlab_total_repositories_timespan_weeks[1h])",
     "legendFormat": "in past: {{in_past}}"
    }
   ]
  },
  {
   "title": "Repositories in last 30 days",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 30 },
   "targets": [
    {
     "expr": "max_over_time(gitlab_total_repositories_timespan_days[10m])",
     "legendFormat": "in past: {{in_past}}"
    }
   ]
  },
  { "title": "Vault", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Vault tokens",
   "type": "barchart",
   "description": "Expiration time for tokens Hashicorp Vault",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(vault_token_expiration_time_seconds[1h])",
     "legendFormat": "{{description}}"
    }
   ]
  }
 ]
}